config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'user_dashboard', to: 'pages#dashboard', as: 'user_dashboard'

  resources :services do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:show, :edit, :update, :destroy] do
      resources :reviews, only: [:new, :create]
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

=begin
                   Prefix Verb   URI Pattern                                                                              Controller#Action
         new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
             user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
     destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
        new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
       edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
            user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
                          PUT    /users/password(.:format)                                                                devise/passwords#update
                          POST   /users/password(.:format)                                                                devise/passwords#create
 cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
    new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
   edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
        user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
                          PUT    /users(.:format)                                                                         devise/registrations#update
                          DELETE /users(.:format)                                                                         devise/registrations#destroy
                          POST   /users(.:format)                                                                         devise/registrations#create
                     root GET    /                                                                                        pages#home
           user_dashboard GET    /user_dashboard(.:format)                                                                pages#dashboard
         service_bookings POST   /services/:service_id/bookings(.:format)                                                 bookings#create
      new_service_booking GET    /services/:service_id/bookings/new(.:format)                                             bookings#new
                 services GET    /services(.:format)                                                                      services#index
                          POST   /services(.:format)                                                                      services#create
              new_service GET    /services/new(.:format)                                                                  services#new
             edit_service GET    /services/:id/edit(.:format)                                                             services#edit
                  service GET    /services/:id(.:format)                                                                  services#show
                          PATCH  /services/:id(.:format)                                                                  services#update
                          PUT    /services/:id(.:format)                                                                  services#update
                          DELETE /services/:id(.:format)                                                                  services#destroy
          booking_reviews POST   /bookings/:booking_id/reviews(.:format)                                                  reviews#create
             edit_booking GET    /bookings/:id/edit(.:format)                                                             bookings#edit
                  booking GET    /bookings/:id(.:format)                                                                  bookings#show
                          PATCH  /bookings/:id(.:format)                                                                  bookings#update
                          PUT    /bookings/:id(.:format)                                                                  bookings#update
       rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
       rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
     rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
=end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  validates :title, :price_per_hour, :location, :description, :category_id, presence: true
  validates :price_per_hour, numericality: { only_integer: true }
  validates :title, uniqueness: { scope: :location }
  # validates :description, length: { in: 20..100 }
  mount_uploader :photo, PhotoUploader

  include PgSearch
  pg_search_scope :search_by_title_and_description,
    against: [ :title, :description ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  def index
    @services = policy_scope(Service)
    if params[:query].present?
      @services = Service.search_by_title_and_description(params[:query])
    else
      @services
    end

    @geocoded_services = @services.geocoded #returns services with coordinates

    @markers = @geocoded_services.map do |service|
      {
        lat: service.latitude,
        lng: service.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { service: service }),
        image_url: helpers.asset_url('man_map_icon.png')
      }
    end
  end


  def show
    @reviews = @service.reviews
    authorize @service
  end

  def new
    @service = Service.new
    authorize @service
  end

  def create
    @service = Service.new(service_params)
    authorize @service
    @service.user_id = current_user.id
    if @service.save
      redirect_to user_dashboard_path
    else
      render 'new'
    end
  end

  def edit
    authorize @service
  end

  def update
    authorize @service
    if @service.update(service_params)
      redirect_to service_path(@service.id), notice: 'Service was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @service
    @service.destroy
      redirect_to user_dashboard_path
  end

  private

  def set_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:title, :price_per_hour, :photo, :location, :description, :category_id)
  end
end

app/views/services/_form.html.erb
<%= simple_form_for service do |f| %>
  <%= f.input :title %>
  <%= f.association :category, as: :select %>
  <%= f.input :description %>
  <%= f.input :location, placeholder: 'Area where you can deliver the service.' %>
  <%= f.input :price_per_hour, hint: 'in dollars' %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.button :submit %>
<% end %>

app/views/services/_infowindow.html.erb
<h2><%= service.title %></h2>
<p><%= service.location %></p>

app/views/services/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">

      <h1>Update your service</h1>

      <%= render 'form', service: @service %>

      <p> <%= link_to 'Back to my service', service_path(params[:id]) %> </p>

    </div>
  </div>
</div>

app/views/services/index.html.erb
<h1 class="m-4" id="page-title"> All services available at the moment</h1>
<div class="main-container">


  <div class="cards-index mx-4">
    <% @services.each do |service| %>
      <div class="card-service" >
        <%= link_to service_path(service.id) do %>
          <%= cl_image_tag service.photo, width: 400, height: 200, crop: :fill %>
        <% end %>
        <div class="card-service-infos">
          <div>
            <h2><%= service.title %></h2>
            <p><%= service.description[0..20]%>...</p>
            <p id="links">
              <% if policy(service).edit? %>
                <%= link_to "Update", edit_service_path(service) %>
              <% end %>

              <% if policy(service).destroy? %>
                <%= link_to 'Delete', service, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </p>
          </div>
          <h2 class="card-service-pricing">$<%= service.price_per_hour %></h2>
          <%= cl_image_tag service.user.avatar, class: "avatar"%>
        </div>
      </div>
    <% end  %>
  </div>

  <div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>

</div>

app/views/services/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">

    <h1>Create a new service</h1>

    <%= render 'form', service: @service %>

    <p> <%= link_to 'Back to all services', new_service_path %> </p>

    </div>
  </div>
</div>

app/views/services/show.html.erb
<div class="main-container m-4">

  <div class="service-image mr-4">
  <%= cl_image_tag @service.photo, height: 300, width: 400, crop: :fill %>
  </div>

  <div class="card-service-infos">

    <h1 id="page-title"><%= @service.title %></h1>
    <h2>Provided by:<%= @service.user.username %></h2>
    <p><%= @service.description %></p>
    <h3><%= @service.location %></h3>
    <h3><%= @service.category.name %></h3>
    $<%= @service.price_per_hour %>
  </div>

</div>



<!-- pundit so someone cannot rent his own service -->
<% unless policy(@service).update? %>
<%= link_to "Hire!", new_service_booking_path(@service.id), class: 'btn btn-primary' %>
<% end %>

<div>

<% if @reviews.empty? %>
  <p>That service hasn't been reviewed yet</p>
<% else %>
  <h1>Reviews</h1>
  <% @reviews.each do |review| %>
    <ul class="list-group list-group-horizontal">
      <li class="list-group-item"><%= review.title%></li>
      <li class="list-group-item"><%= review.rating%></li>
      <li class="list-group-item"><%= review.description%></li>
    </ul>
  <% end %>

<% end %>


<div>
    <!-- pundit so only owner of a service can edit and delete a service -->
    <% if policy(@service).edit? %>
      <%= link_to 'Edit service', edit_service_path(@service.id), class: "btn btn-primary" %>
    <% end %>
      <%= link_to 'Back', services_path, class: "btn btn-primary" %>
    <% if policy(@service).destroy? %>
      <%= link_to 'Delete service', @service, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
      <% end %>
</div>