config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'user_dashboard', to: 'pages#dashboard', as: 'user_dashboard'

  resources :services do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:show, :edit, :update, :destroy] do
      resources :reviews, only: [:new, :create]
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

=begin
                   Prefix Verb   URI Pattern                                                                              Controller#Action
         new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
             user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
     destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
        new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
       edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
            user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
                          PUT    /users/password(.:format)                                                                devise/passwords#update
                          POST   /users/password(.:format)                                                                devise/passwords#create
 cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
    new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
   edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
        user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
                          PUT    /users(.:format)                                                                         devise/registrations#update
                          DELETE /users(.:format)                                                                         devise/registrations#destroy
                          POST   /users(.:format)                                                                         devise/registrations#create
                     root GET    /                                                                                        pages#home
           user_dashboard GET    /user_dashboard(.:format)                                                                pages#dashboard
         service_bookings POST   /services/:service_id/bookings(.:format)                                                 bookings#create
      new_service_booking GET    /services/:service_id/bookings/new(.:format)                                             bookings#new
                 services GET    /services(.:format)                                                                      services#index
                          POST   /services(.:format)                                                                      services#create
              new_service GET    /services/new(.:format)                                                                  services#new
             edit_service GET    /services/:id/edit(.:format)                                                             services#edit
                  service GET    /services/:id(.:format)                                                                  services#show
                          PATCH  /services/:id(.:format)                                                                  services#update
                          PUT    /services/:id(.:format)                                                                  services#update
                          DELETE /services/:id(.:format)                                                                  services#destroy
          booking_reviews POST   /bookings/:booking_id/reviews(.:format)                                                  reviews#create
             edit_booking GET    /bookings/:id/edit(.:format)                                                             bookings#edit
                  booking GET    /bookings/:id(.:format)                                                                  bookings#show
                          PATCH  /bookings/:id(.:format)                                                                  bookings#update
                          PUT    /bookings/:id(.:format)                                                                  bookings#update
       rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
       rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
     rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
=end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :service
  has_one :review
  validates :start_time, :duration, :total_price, :address, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def show
    @booking = Booking.find(params[:id])
    @service = Service.find(@booking.service_id)
    @review = Review.new
    authorize @booking
  end

  def new
    @service = Service.find(params[:service_id])
    @booking = Booking.new
    authorize @booking
    @booking.service_id = params[:service_id]
  end

  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    @service = Service.find(params[:service_id])
    @booking.service = @service
    @booking.user = current_user
    @booking.total_price = @booking.duration * @service.price_per_hour
    if @booking.save
      redirect_to booking_path(@booking.id)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @booking.update(booking_params)
      redirect_to booking_path(params[:id]), notice: 'Booking was successfully updated.'
    else
      render 'edit'
    end
  end

#  def destroy
#    @booking.destroy
#    redirect_to user_dashboard_path
#  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_time, :duration, :total_price, :address, :user_id, :service_id)
  end
end

app/views/bookings/_form.html.erb
  <%= simple_form_for(@booking, as: :booking, method: :post, url: service_bookings_path(params[:service_id])) do |f| %>
    <%= f.input :start_time %>
    <%= f.input :duration, collection: [1, 2, 3, 4, 5] %>
    <!-- for information, i defined ":as => string in the address Input otherwise Algolia autocomplete cannot work with a text area" -->
    <%= f.input :address, :as => :string %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>


<p> <%= link_to 'Back to all services', services_path %> </p>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">

  <h1>Edit your booking's address</h1>

  <%= simple_form_for (@booking) do |f| %>
  <%= f.input :address %>
  <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>

  <p><%= link_to 'Cancel edit mode', booking_path(params[:id]) %></p>

    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>


<div class="container">

<h1> All your bookings available at the moment </h1>

  <% @bookings.each do |x| %>
    <p> <%= x.start_time %>: <%= x.total_price %>€ - <%= link_to 'see details 🔎', bookings_path(x.id) %></p>
  <% end %>

<%= link_to 'Create a new service', new_service_path %>

</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">

  <h3> Book "<%= @service.title %>" for <%= @service.price_per_hour %>€ / h</h3>

  <%= render 'form', booking: @booking %>

    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<h1 id="booking-page"> Reservation n°<%= @booking.id %> - Booked on the <%= @booking.created_at.strftime("%d/%m/%Y") %> </h1>

<h1 id="booking-body"> <%= @service.title %> </h1>

<h1 id="booking-body">Reservation made by: <%= User.find(@booking.user_id).username.capitalize %></h1>

<h1 id="booking-body">Name of the person booked: <%= User.find(@service.user_id).username.capitalize%></h1>

<h1 id="booking-body"> Category: <%= Category.find(@service.category_id).name.capitalize %></h1>


<h1 id="booking-body"> Event date: <%= @booking.start_time.strftime("%A, %d %b %Y %l:%M %p") %></h1>
<h1 id="booking-body"> Event address: <%= @booking.address %></h1>

<h1>Total price: <%= @booking.total_price %> € (<%= @service.price_per_hour %>€ for <%= @booking.duration %> hours)</h1>


<% if DateTime.now >= @booking.start_time %>

  <%= render "reviews/form", booking: @booking, review: @review %>

  <p><%= link_to 'Edit the address of my booking', edit_booking_path(params[:id]) %></p>

  <p><%= link_to 'Back to my dashboard ', user_dashboard_path %></p>

<% else %>
<% end %>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>