config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'user_dashboard', to: 'pages#dashboard', as: 'user_dashboard'

  resources :services do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:show, :edit, :update, :destroy] do
      resources :reviews, only: [:new, :create]
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

=begin
                   Prefix Verb   URI Pattern                                                                              Controller#Action
         new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
             user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
     destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
        new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
       edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
            user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
                          PUT    /users/password(.:format)                                                                devise/passwords#update
                          POST   /users/password(.:format)                                                                devise/passwords#create
 cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
    new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
   edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
        user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
                          PUT    /users(.:format)                                                                         devise/registrations#update
                          DELETE /users(.:format)                                                                         devise/registrations#destroy
                          POST   /users(.:format)                                                                         devise/registrations#create
                     root GET    /                                                                                        pages#home
           user_dashboard GET    /user_dashboard(.:format)                                                                pages#dashboard
         service_bookings POST   /services/:service_id/bookings(.:format)                                                 bookings#create
      new_service_booking GET    /services/:service_id/bookings/new(.:format)                                             bookings#new
                 services GET    /services(.:format)                                                                      services#index
                          POST   /services(.:format)                                                                      services#create
              new_service GET    /services/new(.:format)                                                                  services#new
             edit_service GET    /services/:id/edit(.:format)                                                             services#edit
                  service GET    /services/:id(.:format)                                                                  services#show
                          PATCH  /services/:id(.:format)                                                                  services#update
                          PUT    /services/:id(.:format)                                                                  services#update
                          DELETE /services/:id(.:format)                                                                  services#destroy
          booking_reviews POST   /bookings/:booking_id/reviews(.:format)                                                  reviews#create
             edit_booking GET    /bookings/:id/edit(.:format)                                                             bookings#edit
                  booking GET    /bookings/:id(.:format)                                                                  bookings#show
                          PATCH  /bookings/:id(.:format)                                                                  bookings#update
                          PUT    /bookings/:id(.:format)                                                                  bookings#update
       rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
       rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
     rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
=end

app/views/pages/dashboard.html.erb
<body>


  <span>
    <div class="card-deck-wrapper">
      <div class="card-grid">
        <div class="card1 ml-5">
          <%= cl_image_tag @user.avatar, width: 200, id: 'dash-img' %>
          <div class="card-body">
            <h5 class="card-title"><%= @user.username %></h5>
            <p class="card-text"><%= @user.email %></p>
            <p class="card-text"><%= @user.phone_number %></p>
            <div class="btn btn-primary"><%= link_to 'Edit my Profile', edit_user_registration_path %></div>
          </div>
        </div>
        <div class="card2" style="width: 50rem;">
          <div class="card-body">
            <h1>Your Dashboard</h1>

            <h2>Your Bookings</h2>
            <ul class="ul1">
              <%  @bookings.each do |booking| %>
              <li>
                <%= booking.start_time %>
                <%= booking.service.title %>
                <%= booking.duration %>
                <%= booking.total_price %>
                <%= booking.address %>
                <!-- first solution to only display the booking that hasn't been rated yet-->
                <%# if @reviews.where(booking_id: booking.id).empty? %>
                <!-- second solution to only display the booking that hasn't been rated yet -->
                <% unless booking.review != nil? %>
                <%= link_to 'leave review', new_booking_review_path(booking)%>
                <% end %>
              </li>
              <% end %>
            </ul>
            <h2>Your Services</h2>
            <ul class="ul2">
              <% @services.each do |service| %>
              <li >
                <%= service.title %>
                <%= service.price_per_hour %>
                <%= service.description %>
                <%= service.location %>
                <%= link_to 'x', service_path(service), class: 'btn btn-sm btn-danger', method: :delete %>
              </li>
              <% end %>
            </ul>

            <%= link_to 'Create a Service', new_service_path, class: 'btn btn-primary'  %>
          </div>
        </div>
      </div>
    </span>
  </body>

app/views/pages/home.html.erb
<div class="container-banner" style="background-image: linear-gradient(rgba(0,0,0, -0.7),rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/1353361/pexels-photo-1353361.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940);">
  <div>
  <h1>Who is gonna work for you today?</h1>
  </div>

  <!-- <div class="container-search"> -->
     <%= form_tag services_path, method: :get do %>
    <div class="container-search">
      <%= text_field_tag :query,
        params[:query],
        class: "search-white-bar",
        placeholder: ""
      %>
<!--     </div>
    <div> -->
      <%= submit_tag "search",
      class: "search-button" %>
      <% end %>
    </div>
  <!-- </div> -->

</div>
<!-- Cards --------- Easy find ----------- -->
<div class="container my-4">
  <div class="prospect request">
  <h1 id="page-title">Top categories</h1>
  </div>
</div>
<div class="container">
<div class="cards">

  <a href="/services?utf8=✓&query=Musician">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://media.vanityfair.com/photos/58f1226e50cecc47a7701b89/16:9/w_1280,c_limit/elvis-presley.jpg)">
    Musician
  </div>
  </a>
  <a href="/services?utf8=✓&query=Bodyguard">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://image.shutterstock.com/image-photo/handsome-bodyguard-near-car-outdoors-260nw-716779372.jpg)">
    Bodyguard
  </div>

  </a>
  <a href="/services?utf8=✓&query=Model">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRj4isEI8fnscib-thcr22yS0CmgAzTfJwwdmeklGEo6mAqXqo95A)">

    Model
  </div>
  </a>
  <a href="/services?utf8=✓&query=Impersinator">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwDf0onfA4gGM3XILQsY0XvbkkO5NSVtuUPTugZsV7v9xeV2qJ8g)">
    Impersinator
  </div>
  </a>
  <a href="/services?utf8=✓&query=Actor">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeHBhenV7eLYrG-aBJTUGbXfc22hmq2lAdXJL8zp6HDyIMYliG4Q)">
    Actor
  </div>
  </a>
  <a href="/services?utf8=✓&query=Motivational Speaker">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://assets.entrepreneur.com/content/3x2/2000/1387488102-tony-robbins-7-forces-business-mastery.jpg?width=700&crop=2:1)">
    Motivational Speaker
  </div>
  </a>
  <a href="/services?utf8=✓&query=Coach">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVF5RjBQc6B2eRECMsLL99LCTDshT7xKPZSq4syOAxUEkBFuP0)">
    Coach
  </div>
  </a>
  <a href="/services?utf8=✓&query=Trainer">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://d210i8t551lxm.cloudfront.net/images/contents/000/001/355/original/teacher_teaser.jpg?1504864921)">
    Trainer
  </div>
  </a>
  <a href="/services?utf8=✓&query=Magician">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmLBsawCXdrgp4hrJRSvSx5BufEz0nlbgR7HS3QBBLYvO2__68tA)">
    Magician
  </div>
  </a>
  </div>
</div>